### ISSUE TITLE
封禁的有些太狠了

### ISSUE THREAD

**Issue by w844741652** [trumanwong/ComfyUI-NSFW-Detection#2]
做了一些测试，大概500张的图，有些露脖子的有些也封禁了

**Comment by trumanwong** [comment]
你的阈值设的多少

**Comment by w844741652** [comment]
0，这图都过不了
![11742](https://github.com/trumanwong/ComfyUI-NSFW-Detection/assets/39794671/533885a6-56a2-4747-8a41-1ed9d05251bf)

**Comment by w844741652** [comment]
关键，索隆都过不了，hhhhh
![Uploading 11743.png…]()

**Comment by w844741652** [comment]
![11743](https://github.com/trumanwong/ComfyUI-NSFW-Detection/assets/39794671/2ea071c5-f60b-4dfe-a424-4bf020b98ed3)
关键，索隆都过不了.....

**Comment by trumanwong** [comment]
等我研究会

**Comment by w844741652** [comment]
大神先忙正事，我这不急，就是做stable diffusion模型有一批图，想一遍这个工具。

**Comment by w844741652** [comment]
大神先忙正事，我这不急，就是做stable diffusion模型有一批图，想过一遍这个工具筛选一下。

**Comment by trumanwong** [comment]
你理解错了，score是指将图像分类为 NSFW 的阈值分数，所以如果你要鉴定黄图，不能设成0，应该设置像0.9这样的值
